/*===========================================================================*/
/*                                                                           *
 * Copyright (c) 2020, Computer Graphics Group RWTH Aachen University        *
 *                            All rights reserved                            *
 *                                                                           *
 * Basic Techniques in Computer Graphics Exercise                            *
 *                            DO NOT EDIT THIS FILE!                         *
 *                                                                           */
/*===========================================================================*/

#include <iostream>
#include "assignment.hh"

void solution::drawScene(int scene, float runTime) { std::cout << "\rDrawing " << scene << " at " << runTime << "s.   " << std::endl; }

void solution::initCustomResources() {}

void solution::deleteCustomResources() {}
